// <auto-generated />
using System;
using Backend_RentHouse_Khalifa_Sami.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Backend_RentHouse_Khalifa_Sami.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20200929185311_addPropertyImage")]
    partial class addPropertyImage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Backend_RentHouse_Khalifa_Sami.Model.Property.Property", b =>
                {
                    b.Property<int>("idProperty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("diningRoomArea")
                        .HasColumnType("int");

                    b.Property<float>("fixedChargesCost")
                        .HasColumnType("real");

                    b.Property<byte?>("floor")
                        .HasColumnType("tinyint");

                    b.Property<string>("imageLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("kitchenArea")
                        .HasColumnType("int");

                    b.Property<byte>("nbRoom")
                        .HasColumnType("tinyint");

                    b.Property<float>("rentCost")
                        .HasColumnType("real");

                    b.Property<DateTime>("signatureDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("totalArea")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idProperty");

                    b.ToTable("CommandProp");
                });

            modelBuilder.Entity("Backend_RentHouse_Khalifa_Sami.Model.Property.Property", b =>
                {
                    b.OwnsMany("Backend_RentHouse_Khalifa_Sami.Model.Property.Room", "roomsDetails", b1 =>
                        {
                            b1.Property<int>("idRoom")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("PropertyidProperty")
                                .HasColumnType("int");

                            b1.HasKey("idRoom");

                            b1.HasIndex("PropertyidProperty");

                            b1.ToTable("Room");

                            b1.WithOwner()
                                .HasForeignKey("PropertyidProperty");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
